name: Node CI
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and dist
        run: |
          yarn
          yarn run publish
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and dist
        run: |
          yarn
          yarn run publish
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and dist
        run: |
          yarn
          yarn run publish
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
